command:
  - ${env}
  - python3
  - ivae/main.py
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  tcl:
    value: false
  seed:
    values: [42, 64, 982, 5748, 23567, 8734, 564, 74452, 96, 26]
  # dataset
  num_per_segment:
    value: 1500
  num_segments:
    value: -1  # -> for a small amount of segments, StrNN seem to work better
  source_dim:
    value: 5
  data_dim:
    value: 8
  nl:
    value: 2
  obs_mixing_layers:
    value: 2
  data_seed:
    value: 1
  prior:
    value: 'gauss'
  act:
    value: 'xtanh'
  uncentered:
    value: true
  noisy:
    value: 0
  staircase:
    value: false
  one_hot_labels:
    value: true
  use_sem:
    value: true
  chain:
    value: false
  dag_mask_prob:
    values: [.2, .5, .8]
  data_path:
    value: 'run/datasets/'
  # model args
  n_layers:
    value: 2
  aux_net_layers:
    value: 3
  strnn_layers:
    value: 3
  obs_layers:
    value: 3
  hidden_dim:
    value: 100
  strnn_width:
    value: 100
  ignore_u:
    value: true
  activation:
    value: 'xtanh'
  ica:
    value: true
  initialize:
    value: true
  batch_norm:
    value: false
  tcl:
    value: false
  use_strnn:
    values: [true, false]
  strnn_adjacency_override:
    value: false
  cond_strnn:
    value: false
  separate_aux:
    value: true
  residual_aux:
    value: false

  # learning
  a:
    value: 100
  b:
    value: 1
  c:
    value: 0
  d:
    value: 10
  gamma:
    value: 0
  lr:
    value: 0.01
  batch_size:
    value: 64
  epochs:
    value: 50
  no_scheduler:
    value: false
  scheduler_tol:
    value: 3
  anneal:
    value: false
  anneal_epoch:
    value: 20
  val_freq:
    value: 1
