command:
  - ${env}
  - python3
  - ivae/main.py
method: grid
metric:
  goal: minimize
  name: train_loss
parameters:
  tcl:
    value: false
  seed:
    values: [42, 64, 982, 5748, 23567]
  # dataset
  nps:
    value: 1000
  ns:
    value: 10  # -> for a small amount of segments, StrNN seem to work better
  dl:
    value: 5
  dd:
    value: 5
  nl:
    value: 1
  s:
    value: 1
  p:
    value: 'gauss'
  act:
    value: 'xtanh'
  uncentered:
    value: false
  noisy:
    value: false
  staircase:
    value: false
  one_hot_labels:
    values: [true, false]
  use_sem:
    value: true
  chain:
    values: [true, false]
  data_path:
    value: 'run/datasets'
  # model args
  n_layers:
    values: [1, 2, 3]
  strnn_layers:
    values: [2,3,4]
  hidden_dim:
    values: [50, 100]
  strnn_width:
    values: [20, 40, 80]
  activation:
    value: 'xtanh'
  ica:
    value: true
  initialize:
    value: true
  batch_norm:
    value: false
  tcl:
    value: false
  use_strnn:
    value: true
  separate_aux:
    value: true
  residual_aux:
    value: false

  # learning
  a:
    value: 100
  b:
    value: 1
  c:
    value: 0
  d:
    value: 10
  gamma:
    value: 0
  lr:
    value: 0.01
  batch_size:
    value: 64
  epochs:
    value: 20
  no_scheduler:
    value: false
  scheduler_tol:
    value: 3
  anneal:
    value: false
  anneal_epoch:
    value: 20
